node_js:
 - "10"

services:
 - postgresql

before_install:
 - psql -c 'create database testdatabase' -U postgres

after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
 - npm install
 - npm run test

after_success:
 - npm run coverage

cache:
 directories:
   - "node_modules"